import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import AuthSession from "@/app/_components/AuthSession";
import RQProvider from "@/app/_components/RQProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RQProvider>
          <AuthSession>{children}</AuthSession>
        </RQProvider>
      </body>
    </html>
  );
}
